#!/bin/bash
export QUESTION='总办会 总经理办公会 总裁办公会 审议 审批 决策 批准'
export PAGE_SIZE=100
export SIMILARITY_THRESHOLD=0.3
export VECTOR_SIMILARITY_WEIGHT=0.7
python ./search.py
rm -rf ~/Downloads/*csv
mv *csv ~/Downloads/